### ISSUE TITLE
Header not available in some cases

### ISSUE THREAD

**Issue by Neofox** [yoctu/api-gardian#1]
When used with Apache, in some cases the Header `Authorization` will not be available in  `$_SERVER`. 

For the moment we would need to add the rule `SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1` in the apache conf to get the code working.

Maybe with the use of `apache_request_headers()` we can get the header anyway.

**Comment by dzove855** [comment]
We should test it, because it's tricky if the Header is available with this function, because normally Apache doesn't send the headers

**Comment by Neofox** [comment]
I did, and for an obscur reason it worked...

**Comment by dzove855** [comment]
holy crap, what insecure solution hahahaha
(I'm talking about php)

**Comment by lvenier** [comment]
api-guardian is opensource and can be deployed for any objective application.
Then we can have people with nginx using this feature. Does the apache_request_header working for nginx ?

**Comment by Neofox** [comment]
It should work, but I added a little check in the code for the worst case scenario : 
```php
$apacheHeaders = [];
if (\function_exists('apache_request_headers')) {
    $apacheHeaders = apache_request_headers();
}
```
if the apache extension is not enabled ( because we only want to use nginx for example) the function will not be used and the code should work like before

**Comment by lvenier** [comment]
I would go for :
$httpHeaders = [];
if (\function_exists('apache_request_headers')) {
    $httpHeaders = apache_request_headers();
}

Looks more generic to me. opinion ?

**Comment by Neofox** [comment]
those kind of choices should be discussed in the pull request ( https://github.com/yoctu/api-guardian/pull/2 ) 
but yeah, I can do that
